name: Build Docker Image
description: Build Docker Image
inputs:
  path_dockerfile:
    description: Dockerfile Path
    default: 'Dockerfile'
    required: false
  image_name:
    description: Docker Image Name
    default: 'academy'
    required: false
  tag_name:
    description: Docker Image Tag Name
    default: ''
    required: false
runs:
  using: composite
  steps:
    - name: Set Docker Image properties
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
        echo "DOCKER_IMAGE_NAME=${{inputs.image_name}}" >> $GITHUB_ENV
      shell: bash
    - name: Find Docker Image
      run: docker images|grep academy
      shell: bash

