name: Push Docker Image to DockerHub
description: Build Docker Image
inputs:
  docker_username:
    description: DockerHub Username
    default: ''
    required: true
  image_name:
    description: Docker Image Name
    default: 'academy'
    required: false
  tag_name:
    description: Docker Image's Tag
    default: ''
    required: false
runs:
  using: composite
  steps:
    - run: docker image tag ${{ inputs.image_name }}:${{ inputs.tag_name }} ${{ inputs.docker_username }}/academy_repo:${{ inputs.tag_name }}
      shell: bash
    - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/academy_repo:${{ inputs.tag_name }}
      shell: bash
